parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'

        types:
            money: App\Infrastructure\Doctrine\DBAL\MoneyType
            currency: App\Infrastructure\Doctrine\DBAL\CurrencyType
            datetime: App\Infrastructure\Doctrine\DBAL\UTCDateTimeType
            week: App\Infrastructure\Doctrine\DBAL\WeekType
            domain: App\Infrastructure\Doctrine\DBAL\DomainType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        entity_listener_resolver: app.doctrine.entity_listener_resolver
        mappings:
            Infrastructure:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Resources/config/doctrine/infrastructure'
                prefix: 'App\Infrastructure'
                alias: Infrastructure
            Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Resources/config/doctrine/domain'
                prefix: 'App\Domain'
                alias: Domain

        dql:
            datetime_functions:
                date:  App\Infrastructure\Doctrine\DQL\Date
                year:  App\Infrastructure\Doctrine\DQL\Year
