version: '3'

services:
    db:
        image: mysql:5.7
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - "./var/data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
