version: '3'

services:
    db:
        image: mysql:5.7
        ports:
            - 3316:3306
        volumes:
            - "./var/data_test/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: investment_manager
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
