<?php

namespace App\Infrastructure\EventSource;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * @method Changed|null find($id, $lockMode = null, $lockVersion = null)
 * @method Changed|null findOneBy(array $criteria, array $orderBy = null)
 * @method Changed[]    findAll()
 * @method Changed[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
final class EventSourceRepository extends ServiceEntityRepository implements EventSourceRepositoryInterface
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Changed::class);
    }

    /**
     * @inheritDoc
     */
    public function findEvents(string $id, string $typeName, int $fromNumber = 1, int $count = null): array
    {
        return $this->createQueryBuilder('c')
            ->andWhere('c.aggregateId = :id')
            ->setParameter('id', $id)
            ->andWhere('c.aggregateType = :typeName')
            ->setParameter('typeName', $typeName)
            ->andWhere('c.aggregateVersion >= :fromNumber')
            ->setParameter('fromNumber', $fromNumber)
            ->setMaxResults($count)
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * @inheritDoc
     */
    public function saveEvents(ArrayCollection $changes, bool $flush = false)
    {
        foreach ($changes as $change) {
            $this->_em->persist($change);
        }

        if ($flush) {
            $this->_em->flush();
        }
    }

    public function count(array $criteria)
    {
        return parent::count($criteria); // TODO: Change the autogenerated stub
    }
}
