menu:
  FinanceTransferMenuItem:
    label: 'Finance'
    icon: 'fas fa-book'
    items:
      FinanceTransferMenuItem:
        label: 'Transfers'
        icon: 'fa fa-cash-register'
        route: 'transfer_index'
      FinanceAccountsMenuItem:
        label: 'Accounts'
        icon: 'fa fa-credit-card'
        route: 'account_index'
  MarketMenuItem:
    label: 'Market'
    icon: 'fas fa-landmark'
    items:
      MarketStockMarketMenuItem:
        label: 'Stock Market'
        icon: 'fas fa-industry'
        route: 'stock_market_index'
      StockMenuItem:
        label: 'Stock'
        icon: 'fas fa-money-bill'
        route: 'stock_index'
      BrokerMenuItem:
        label: 'Broker'
        icon: 'fas fa-business-time'
        route: 'broker_index'
      WalletMenuItem:
        label: 'Wallet'
        icon: 'fas fa-wallet'
        route: 'wallet_index'
