menu:
  FinanceTransferMenuItem:
    label: 'Finance'
    icon: 'fa fa-bars'
    items:
      FinanceTransferMenuItem:
        label: 'Transfers'
        icon: 'fa fa-cash-register'
      FinanceAccountsMenuItem:
        label: 'Accounts'
        icon: 'fa fa-credit-card'
        route: 'account_index'

