### Successful test: check response status is 200 account
GET http://localhost:8080/v1/accounts/{{account_id}}
Accept: application/json

> {%
    client.test("Response status", function() {
        var status = response.status;
        client.assert(status === 200, "Expected `200` but received '"+ status + "'");
    });

    client.test("Response mimeType", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

    var account = response.body.item;
    client.test("Response item", function() {
        client.assert(account !== undefined, "Response item is null");
        client.assert(account.name === client.global.get("account_name"), "Response item name is not equals");
        client.assert(account.accountNo === client.global.get("account_accountNo"), "Response item accountNo is not equals");
        client.assert(account.alias === client.global.get("account_alias"), "Response item alias is not equals");
        client.assert(account.title === client.global.get("account_title"), "Response item title is not equals");
    });
%}

### Successful test: check response status is 200 accounts
GET http://localhost:8080/v1/accounts/
Accept: application/json

> {%
    client.test("Response status", function() {
        var status = response.status;
        client.assert(status === 200, "Expected `200` but received '"+ status + "'");
    });

    client.test("Response mimeType", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}
###
